# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install required Python packages
RUN pip install redis jsonpickle requests flask minio

# Run the rest server
CMD ["python", "server_rest.py"]
